services:
  - type: web
    name: rechnungsjob
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: EMAIL_USER
        fromRender: true
      - key: EMAIL_PASS
        fromRender: true
      - key: DROPBOX_TOKEN
        fromRender: true
