services:
  - type: web
    name: rechnungsjob
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:10000 main:app --timeout 120"
    envVars:
      - key: EMAIL_USER
        fromEnvVar: EMAIL_USER
      - key: EMAIL_PASS
        fromEnvVar: EMAIL_PASS
      - key: DROPBOX_TOKEN
        fromEnvVar: DROPBOX_TOKEN
